### ISSUE TITLE
ncm-yaim: rpmlint files on empty file

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-grid#109]
```
ncm-yaim.noarch: E: zero-length /usr/lib/ncm/config/yaim/empty
```

**Comment by stdweird** [comment]
i've tagged this for 16.6, but might harmless enough to move to 16.8

**Comment by jrha** [comment]
Fixed by removing ncm-yaim in #122

**Comment by stdweird** [comment]
@jrha george ran into this yesterday, but i don't know his github handle to ping him about this

**Comment by jrha** [comment]
@gvasilak
