### ISSUE TITLE
ncm-glitestartup: rpmlint fails on detected bash script

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-grid#110]
```
ncm-glitestartup.noarch: E: non-executable-script /usr/lib/ncm/config/glitestartup/gLite.template 0644L /bin/bash
```

**Comment by stdweird** [comment]
i've tagged this 16.6, if this harmless, can be moved to 16.8

**Comment by jouvin** [comment]
I'll try to look at it. `gLite.template` is, if I am right, the template for the init script.

**Comment by jouvin** [comment]
I had a look at this. In fact there is no way (at least I found none!) to tell `rpmlint` to ignore errors on some files. The only way to clear this error is to make this template executable which is a non sense... I tend to prefer keeping this error as expected in this particular case until we rewrite ncm-glitestartup without `ncm-template`.

**Comment by stdweird** [comment]
#111 sort-of fixes it. it's not pretty, but neither is the the so-called template. it would be better if the init.d script was shipped as a script (and also not by a quattor component), and that the script does a 
```
if [ -f /etc/sysconfig/giltestartup ]; then
    . /etc/sysconfig/giltestartup
fi
```
and that the component (or another component) generates the sysconfig file

**Comment by jouvin** [comment]
@stdweird Good suggestion, I opened #112.
