### ISSUE TITLE
ncm-glitestartup: remove usage of ncm-template

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-grid#112]
`ncm-glitestartup` currently relies on the obsolete `ncm-template` to produce the init script. As suggested by @stdweird in #110, this could probably be replaced by using a `/etc/sysconfig/glitestartup` file to pass the execution parameters to the script.

**Comment by jrha** [comment]
Closing as `wontfix` as I'm assuming that no-one uses the component any more.
