### ISSUE TITLE
ncm-wmslb: replace use of ncm-template by CAF::TextRender

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-grid#52]
`ncm-wmslb` still relies on obsolete `ncm-template`. `CAF::TextRender` is the obvious replacement...

**Comment by jrha** [comment]
Any progress?

**Comment by jouvin** [comment]
No, for next release may be...

**Comment by jrha** [comment]
Bumped.

**Comment by jouvin** [comment]
WMSLB no longer exists. Component can be deprecated. Won't fix it.
