### ISSUE TITLE
ncm-glitestartup: remove LC::Check usage for directories

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-grid#58]
#56 replaced LC::Check calls by CAF for the management of files. But 2 LC::Check calls are still present, to  manage a directory. The alternative to LC::Check is not clear:
- LC::Check::directory can probably be replaced by File::Path::make_path, despite it is not clear from the documentation that it doesn't raise an error if the directory already exists...)
- LC::Check::status applied to a directory allows to modify owner/group/perm of an existing directory: suggested replacement by File::Path doesn't allow it (File::Path does not modify metadata of an existing directory)

Do we need a `CAF::FileStatus` module that will implement `status` for directory? See https://github.com/quattor/CAF/issues/69 for the discussion on this topic...

Suggestions welcome...

**Comment by jrha** [comment]
Closing as `wontfix` as I'm assuming that no-one uses the component any more.
