### ISSUE TITLE
Bump build tools to 1.40

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-grid#64]
I was sure I had done it (at least to 1.39) but it seems I forgot to push the changes. I'm trying to do it by tomorrow. Else if it doesn't prevent building the release, just postpone to 15.2.

**Comment by jouvin** [comment]
Done. Note that updatding build tools is very easy with maven and should probably be documented somewhere. Just enter in the top-level directory of any Quattor repo:

```
maven versions:update-parent
```

**Comment by stdweird** [comment]
@jouvin thanks for the tip!
