### ISSUE TITLE
15.2.0-rc5: ncm-lcgbdii broken

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-grid#68]
This is a showstopper for 15.2.0 release (https://github.com/quattor/release/issues/81). After upgrading to 15.2.0-rc5, `ncm-lcgbdii` fails with the following error despite there was no recent change to the component. A side-effect of `CAF` modifications?

```
2015/03/19-14:59:47 -----------------------------------------------------------
2015/03/19-14:59:47 [ERROR] error filling template /usr/lib/ncm/config/lcgbdii/lcgbdii.template
2015/03/19-14:59:47 [INFO] configure on component lcgbdii executed, 1 errors, 0 warnings
```

**Comment by stdweird** [comment]
can you try to send `--debug 5` output?

**Comment by jouvin** [comment]
Problem understood... nothing to do with `CAF`! This is a side effect of maven tools changes: the template file is no longer part of the RPM. I'm looking at the easiest way to fix it.

**Comment by jouvin** [comment]
BTW, this problem also affects other compents using a template file, like `ncm-glitestartup`.

**Comment by jouvin** [comment]
Sorry for the delay, I have been interrupted a lot this afternoon... So the problem is not caused by the maven tools changes but by the cleanup done in `pom.xml` files during commit 84367a0a8c132344c4f0494519df55a9bcd09f43. I am working on fixing it.

**Comment by jrha** [comment]
Thanks :smile:
