### ISSUE TITLE
ncm-pbsserver module cannot fill the /var/torque/server_priv/nodes when the file is empty

### ISSUE THREAD

**Issue by Pansanel** [quattor/configuration-modules-grid#76]
When installing a new pbs-server, the /var/torque/server_priv/nodes file provided by the RPM is empty. As you can see on the following part of the code:
https://github.com/quattor/configuration-modules-grid/blob/master/ncm-pbsserver/src/main/perl/pbsserver.pm#L279
if the file is empty, the part of the code in charge of filling the file is not executed.
Another thing, if the file is missing, it is not created. Is there a good reason for that?

**Comment by stdweird** [comment]
@Pansanel that part of the code does not fill the `nodes` file (or reads it). `ncm-pbsserver` doesn't touch the `nodes` file directly, it parses output from `pbsnodes -a` and uses `qmgr` to add/change nodes.
i rememeber an issue with older torque versions that `qmgr` didn't flush the state set in qmgr to the `nodes` file, but that was a bug in torque, not the component.

**Comment by Pansanel** [comment]
In fact, the /var/torque/nodes files is filled with the command on line 317:
`$self->runCommand($qmgr, "create node $node") unless (defined($existingnodes{$node}));`
However, it works only if the `$existingnodes{$node}` variable is set. This is done in the previous block, that is skipped if the /var/torque/nodes file is empty

**Comment by stdweird** [comment]
@Pansanel a node is only created if it didn't not exist before. not sure what is wrong with that (if they already exist, they are updated, not recreated).

**Comment by stdweird** [comment]
@Pansanel is this still an issue? if so, can you give the torque version you are seeing this with?

**Comment by Pansanel** [comment]
I have this issue with torque-server-2.5.13.

**Comment by jrha** [comment]
Is anyone still actually using torque?

**Comment by wdpypere** [comment]
We don't at our site.

**Comment by jrha** [comment]
Closing with `wontfix`, if someone is still using this component, feel free to re-open.
