### ISSUE TITLE
ncm-pbsserver: component executes all qmgr statements every run

### ISSUE THREAD

**Issue by wdpypere** [quattor/configuration-modules-grid#81]
causing some of them to fail.

**Comment by stdweird** [comment]
some issues after short review
* don't run commands that won't change anything
* run commands batched, e.g. per node (or insert short sleep per command to avoid issue above)
* get rid of `qx/pbsnodes`, use `qmgr-c "p n @master"` call
* use FileWriter
* don't set properties of nodes/queues that will be deleted

**Comment by jrha** [comment]
Assuming this is long obsolete, so closing with `wontfix`
