### ISSUE TITLE
DPM LFC unittest fails on EL5

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-grid#92]
@jrha @jouvin this will affect the release

```
src/test/perl/value_format..........1..18
[VERB] Log options --verbose
ok 1 - Boolean (false) correctly formatted
ok 2 - Boolean (true) correctly formatted
ok 3 - Boolean (true, quoted) correctly formatted
ok 4 - Literal value correctly formatted
ok 5 - Literal value (quoted) correctly formatted
ok 6 - Quoted literal value correctly formatted
not ok 7 - Already quoted literal value correctly formatted

#   Failed test 'Already quoted literal value correctly formatted'
#   at src/test/perl/value_format.t line 83.
#          got: '""This is a Test""'
#     expected: '"This is a Test"'
not ok 8 - Already single quoted literal value correctly formatted

#   Failed test 'Already single quoted literal value correctly formatted'
#   at src/test/perl/value_format.t line 89.
#          got: '"'This is a Test'"'
#     expected: ''This is a Test''
ok 9 - Empty value correctly formatted
ok 10 - Empty value (quoted) correctly formatted
ok 11 - Instance params correctly formatted
ok 12 - Instance params (quoted) correctly formatted
ok 13 - Array values correctly formatted
ok 14 - Array values (sorted) correctly formatted
ok 15 - Array values (unique) correctly formatted
ok 16 - Hash keys correctly formatted
ok 17 - no warnings
ok 18 - no warnings

```

**Comment by jrha** [comment]
Well at least it won't prevent it, I don't build on EL5 :smiling_imp:
@jouvin Does it need EL5 support? If so what's the likelihood of a fix?

**Comment by stdweird** [comment]
@jouvin one of the difference between perl5.8.8 and later 5.10+ is that 5.8.8 does not support named groups. so if you are using those somewhere, try to rewrite the regexps.

**Comment by stdweird** [comment]
@jouvin if you do not expect this to work on el5, i'll exclude this from the el5 build test

**Comment by stdweird** [comment]
@jouvin ping?

**Comment by jouvin** [comment]
I'll have a look...

**Comment by jouvin** [comment]
I had a look. Would be better to fix it as it also impact RuleBasedEditor in fact... Do you know how to replace `\g1` (the string that matched the first group) in perl 5.8.8?

**Comment by stdweird** [comment]
not sure what you mean. what regexp is used? and a small example?

**Comment by jouvin** [comment]
The failing regexp is `/^(["']).*\g1$/` used to match a quoted string, no matter whether it is quoted or double quoted.
BTW, the problem in `ncm-dpmlfc` will be fixed by #97 as this code has been moved to the RuleBasedEditor. But it would be good to fix it if possible and easy. An acceptable alternative for me would be to make an explicit comment that quoted values are not supported on SL5. This is not a problem for `ncm-dpmlfc` itself (thus the reason I missed it on SL5 machines using the config module but where the tests are not executed).

**Comment by jouvin** [comment]
I had a look at this but I don't see any solution to implement the same in perl 5.8 (at least one reasonable solution!). The only thing I see for a 5.8 support of this quoting feature is to relax the pattern and look for any occurence of `'` or `" ` at the beginning and at the end of the pattern, without correlating both. Thus `"this is an improperly quoted text'` would match (except if we do an additional check to compare the first and last character)... I think that until we need a real support on SL5 (I hope never!), we could live with a comment about the SL5 restriction.
Any other opinion or proposal.

**Comment by jouvin** [comment]
Too quick to comment! `\1` seems to do the job, will change for it. I thought it would match either single or double quote, as in the first group but it seems to match the alternative that matched in first group.

**Comment by jouvin** [comment]
Fixed in https://github.com/quattor/CAF/pull/151. I think this issue can be closed now.
