### ISSUE TITLE
ncm-dpmlfc: typo srm22 -> srmv22

### ISSUE THREAD

**Issue by victor-mendoza** [quattor/configuration-modules-grid#95]
There is a typo in line 339 of ncm-dpmlfc/src/main/perl/dpmlfc.pm that prevents the component from properly generating the "DPNS TRUST" line in the /etc/shift, "srm22" should be changed to "srmv22".

**Comment by jouvin** [comment]
I'm having a look at it. Thanks for spotting this typo: I'm surprise it didn't heart earlier...
